apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: flask-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      serviceAccountName: flask-api-sa
      containers:
      - name: flask-api
        image: 533046675336.dkr.ecr.eu-north-1.amazonaws.com/valya-lab:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: DB_HOST
          value: postgres.flask-api.svc.cluster.local
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: POSTGRES_DB
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: POSTGRES_DB_PORT
