apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=        # same base64 username as postgres-secret
  DB_PASSWORD: cGFzc3dvcmQ=    # same base64 password as postgres-secret
