apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: flask-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      serviceAccountName: flask-api-sa
      containers:
      - name: flask-api
        image: 533046675336.dkr.ecr.eu-north-1.amazonaws.com/valya-lab:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: db-config
        - secretRef:
            name: db-credentials
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3